name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.11'

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests and coverage
        run: flutter test --coverage
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
