name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1'

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests and coverage
        run: flutter test --coverage && bash <(curl -s https://codecov.io/bash)